### ISSUE TITLE
Feature 14: User can play a medley of bookmarked sounds

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/SoundButtonFuze#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Listen to a medley of bookmark sounds
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User clicks on the play medley button and plays the sounds with .5s delay in between

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update component to include function component that plays all sounds
- [x] Loop through state sound prop
- [x] delay sound.play() .5s

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
