### ISSUE TITLE
Bug: When user logs in within sound-detail page 'Add to Bookmark' is displayed

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/SoundButtonFuze#56]
#### Desired Behavior

> ##### The app should ...

The app should display remove button when sound is in bookmark

#### Actual Behavior

> ##### The app does this instead ...

The app displays add to bookmark when logging in within the sound-detail page regardless if sound is in bookmark

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

1. Add sound to bookmark
2. Log out
3. Go to bookmarked sound-detail page
4. Sign in

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
