### ISSUE TITLE
Polish: Revise sign-out button 

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/SoundButtonFuze#57]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can sign-out, submit recording, play medley

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Apply css to revise appearance of buttons

## ✅ Task List

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
