### ISSUE TITLE
Bug: Bookmarked medley does not stop playing when hash change occurs

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/SoundButtonFuze#60]
#### Desired Behavior

> ##### The app should ...

The app should stop playing sounds when hash change occurs or when another sound is played
#### Actual Behavior

> ##### The app does this instead ...

The medley plays until it is finished regardless
#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Play medley
## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
